package co.edu.usa.talentotech.sga.mail;

public class MessageHtml {

	public static final String TEMPLATE_EMAIL ="\r\n"
			+ "    <table class=\"es-content-body\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
			+ "        <tbody>\r\n"
			+ "            <tr>\r\n"
			+ "                <td class=\"esd-structure es-p20t es-p40r es-p40l es-m-p20r es-m-p20l\" align=\"left\" esd-custom-block-id=\"1048706\">\r\n"
			+ "                    <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
			+ "                        <tbody>\r\n"
			+ "                            <tr>\r\n"
			+ "                                <td class=\"es-m-p0r es-m-p20b esd-container-frame\" width=\"520\" valign=\"top\" align=\"center\">\r\n"
			+ "                                    <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
			+ "                                        <tbody>\r\n"
			+ "                                            <tr>\r\n"
			+ "                                                <td align=\"center\" class=\"esd-block-image\" style=\"font-size:0px;\"><a target=\"_blank\" href=\"http://localhost:4200/signin\"><img class=\"adapt-img\" src=\"https://www.manosverdes.co/wp-content/uploads/2021/02/manejo-de-la-basura-imagen-destacada.jpg\" style=\"display: block;\" width=\"520\" title=\"\"></a></td>\r\n"
			+ "                                            </tr>\r\n"
			+ "                                            <tr>\r\n"
			+ "                                                <td align=\"left\" class=\"esd-block-text\">\r\n"
			+ "                                                    <h2 style=\"color: #15803d;\">Hola, userName</h2>\r\n"
			+ "                                                    <p>Nos alegra que quieras ser parte de nuestro sistema de gestion ambiental para el manejo de residuos.</p>\r\n"
			+ "                                                    <p>A continuación encontrarás tus credenciales para ingresar:</p>\r\n"
			+ "                                                    <p><br></p>\r\n"
			+ "                                                    <p><b style=\"color: #15803d;\">Usuario:</b>userEmail</a></p>\r\n"
			+ "                                                    <p><b style=\"color: #15803d;\">Contraseña: </b>userPassword<br></p>\r\n"
			+ "                                                    <p><br></p>\r\n"
			+ "                                                    <p><b style=\"color: #15803d;\">Atentamente</b></p>\r\n"
			+ "                                                    <p>El equipo de Sga Residuos</p>\r\n"
			+ "                                                    <p><a href=\"mailto:dificultadpruebas@pragma.com.co\" target=\"_blank\"></a></p>\r\n"
			+ "                                                </td>\r\n"
			+ "                                            </tr>\r\n"
			+ "                                        </tbody>\r\n"
			+ "                                    </table>\r\n"
			+ "                                </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                        </tbody>\r\n"
			+ "                    </table>\r\n"
			+ "                </td>\r\n"
			+ "            </tr>\r\n"
			+ "        </tbody>\r\n"
			+ "    </table>";
}
